artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://storage.googleapis.com/kaggle-data-sets/4458/8204/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20250212%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250212T174601Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=3623b6ad12ba14e5c172bc2edeb0aa21515957ad7a2ade2297e11bea6a19766c142944cf80b804adfc01be85c381b42fb7805d378ff52a4794c42f6d6986a634a3ba61ffa32075839bdd9a08383f28b25bdbcfc2eeca8a4025b5063433e2e6b669f21a5f0eadf25685875705f3b4dfb2aa8a8b152654626a469570b37d3f4be275cd3a1b12ca76e7cbfb2c3df7c2840a3cca99679bc6979989d3faec0d63783da70e0a7614e56c6290eefda4306d59825a9c328ea4c784daeb8bfe8a85bcce63743fd418b5f076618bb07995beea2a470f19b5e2e011b516caf7c83bdf184b2641ce3206c04e65da496bde9a737fbef5c9cb063edb2ed6687ae70902ff9baf72
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv



model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
