artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://storage.googleapis.com/kaggle-data-sets/4458/8204/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20250220%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250220T213345Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=47b1bce7d4101e3032047f860529f1ced5401e73d4b23c6714533aa31ce4264aacb7b9d321c27c7d8a9acac223d20bee6f0003641b58bd9cf0d2b9992a7e4b67dc872a45d823c1d3917a540afea15899fa5251a901b3cc2570e6e676f55866a02f5cc83e4bf8e8a1bf8cd795b3420bb6f8fc30818be0a8342d4e986196c36eaddecf7288404cf95799ff73a7d90faab07b725c875ab40175d054764b61d95b7cda376a911e5e1c21fc435079514e1fe70b8ce60b28fd75334ef65e336d12b8a7e835e4e68a6ee8b40ac26c8006d7436418239cf7264e866ce2dc1a21cd96c07a58ed88ba955e7b6616c7aa34e3732d381599924e2069e382532a500f9e3d6f4a
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv



model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
